services:
  app:
    build: .
    image: mini-project:product-pos
    container_name: product-pos-server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/product-pos