services:
  app:
    build: .
    image: mini-project:product-pos
    container_name: product-pos-server
    command: sh -c " python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && wait"
    ports:
      - 8000:8000
    volumes:
      - .:/product-pos