# Generated by Django 4.2.2 on 2023-06-19 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_choice', models.CharField(max_length=225)),
                ('add_on_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_choice', models.CharField(max_length=225)),
                ('size_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.ManyToManyField(to='product_app.addon')),
                ('size', models.ManyToManyField(to='product_app.size')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=225)),
                ('product_price', models.FloatField()),
                ('product_type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('variation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.variation')),
            ],
        ),
    ]
